remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: NMLT - NTTMK - K18
description: UIT - K18 - Nhập môn lập trình - Thầy Nguyễn Tấn Trần Minh Khang
show_downloads: true

# REPO DOWNLOAD LINK
github_repo_link:
  1-167-main: https://github.com/NMLT-NTTMK-K18/1-167-main-B-K
  2-167-func: https://github.com/NMLT-NTTMK-K18/2-167-func-B-K
  3-194-array: https://github.com/NMLT-NTTMK-K18/3-194-array
  4-172-matrix: https://github.com/NMLT-NTTMK-K18/4-172-matrix
  5-258-struct: https://github.com/NMLT-NTTMK-K18/5-258-struct
  6-191-recursion: https://github.com/NMLT-NTTMK-K18/6-191-recursion
  7-200-wecode: https://github.com/NMLT-NTTMK-K18/7-200-wecode